name : "Hello World"

on :
    push:

env:
    API_KEY : ${{ secrets.APP_NAME}}
    TARGET : "World"
    MESSAGE : ${{ secrets.MESSAGE }}
jobs :
    hello :
        runs-on : ubuntu-latest

        steps : 
            - name : Say
              run : echo "Hello world"

            - name : Say Hello
              run : echo "${{ env.GREETING }} ${{ env.TARGET }}"

            - name : Say Message
              run : echo "${{ env.MESSAGE }}"

            - name : Say API Key
              run : |
                    echo "API Key : ${{ env.API_KEY }}"
                    if : API_KEY is not empty , then echo "API KEY is Set" else echo "API KEY is not set"
                    