name : "Hello World"

on :
    push:

env:
    GREETING : "Hello"
    TARGET : "World"
    MESSAGE : "Welcome to the world of GitHub Actions"
jobs :
    hello :
        runs-on : ubuntu-latest

        steps : 
            - name : Say
              run : echo "Hello world"

            - name : Say Hello
              run : echo "${{ env.GREETING }} ${{ env.TARGET }}"

            - name : Say Message
              run : echo "${{ env.MESSAGE }}"